### ISSUE TITLE
how to run the code

### ISSUE THREAD

**Issue by Akash-Platinum** [Malemm/ml-graphology#17]
can you please tell me how to run the code step by step , i read the read.me file but didn't understand how to run the code as i am a complete beginner can u explain how and where ( like vs code , atom ) to run the code on my laptop ,,

**Comment by titanh3art** [comment]
Hi, you can run the code like you run any python script. If you are using IDE, it could provide a run button to execute the script, that depends on your IDE. You can find plenty of tutorials/guide in the internet.

You can simply execute `python <script_name>.py` in your terminal or command prompt to run any `<script_name>.py`.
