### ISSUE TITLE
Can you attach the images, or the link to the dataset of images?

### ISSUE THREAD

**Issue by prawigya** [Malemm/ml-graphology#2]

**Comment by titanh3art** [comment]
Here you go.
http://www.fki.inf.unibe.ch/databases/iam-handwriting-database

**Comment by titanh3art** [comment]
The images should be rid of the printed text areas. It's necessary to scale all the images to a uniform resolution (width) to be able to extract each line of handwriting. Then set a suitable value for constants like `MIDZONE_THRESHOLD` in `extract.py` accordingly.
