### ISSUE TITLE
hello im facing a issue , i think i have not uploaded the data but i want to ask how to do that?

### ISSUE THREAD

**Issue by amysinghoberoi** [Malemm/ml-graphology#3]
File "extract.py", line 760, in start
    barometer(image)

  File "extract.py", line 709, in barometer
    image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

**Comment by maheshm50719** [comment]
> File "extract.py", line 760, in start
> barometer(image)
> 
> File "extract.py", line 709, in barometer
> image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
> 
> error: OpenCV(4.1.1) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

can u help how u load the images

**Comment by nadarsrishtti** [comment]
how can i contact you ??
really need help with the data sets ??

**Comment by maheshm50719** [comment]
Sir how can i upload my own dataset and sir how you extract the feature of
images in binary format can u please help me for that.
It will be really helpful for me.
My contact number is :8857029389

**Comment by nadarsrishtti** [comment]
Thank you so much for connect with me. But I switch to other project it was
an urgent need...

Good Day Sir.

**Comment by titanh3art** [comment]
Hi, regarding dataset please check the update README file.
