### ISSUE TITLE
Understanding related to labeling 

### ISSUE THREAD

**Issue by arhamtariq** [Malemm/ml-graphology#4]
I just want simple explanation regarding to the outcomes of the proposed algorithim. Just clarify that what is the interpretation of the following outcome
![Result_1](https://user-images.githubusercontent.com/26552843/75130965-ae072680-56f2-11ea-9d23-7d67ca72a0a7.png)
For example my question is that if Result states that Emotional stability is [1]. Can we deduce that person is Emotionaly stable or not ?. Or if Lack of Discipline is [0]. So Can we interept that the person has **No** Issue regariding to discipline?

**Comment by aineelz** [comment]
> I just want simple explanation regarding to the outcomes of the proposed algorithim. Just clarify that what is the interpretation of the following outcome
> ![Result_1](https://user-images.githubusercontent.com/26552843/75130965-ae072680-56f2-11ea-9d23-7d67ca72a0a7.png)
> For example my question is that if Result states that Emotional stability is [1]. Can we deduce that person is Emotionaly stable or not ?. Or if Lack of Discipline is [0]. So Can we interept that the person has **No** Issue regariding to discipline?

Can you excute this code?

**Comment by titanh3art** [comment]
Hi, I have put the thesis of the project itself in the repo. Please check.
