### ISSUE TITLE
Doubts on the Dataset used.

### ISSUE THREAD

**Issue by Kusumadhanush22** [Malemm/ml-graphology#5]
What is the data set used for this project?

**Comment by titanh3art** [comment]
Hi, I got them from here http://www.fki.inf.unibe.ch/databases/iam-handwriting-database

**Comment by chaitu0032-debug** [comment]
I have seen the database of 1AM and cannot find the the labelled traits
can u. help me with that please

**Comment by titanh3art** [comment]
Hi, please check the updated README file
