### ISSUE TITLE
I've updated this project for Python 3 

### ISSUE THREAD

**Issue by art3m1s-dev** [Malemm/ml-graphology#7]
Hey, there! I really wanted to try out your project, but this OpenCV doesn't work on Python 2 anymore. So I managed to patch it for python 3.9 (version I'm currently on). I added some parenthesis around all the print functions, modified new functions, fixed one typo in the name of a variable, added some if statements for variables trying to divide themselves by 0 and got it up and running! I've submitted two pull requests: one for train_predict.py, and one for extract.py. Take a look and merge them if you approve

**Comment by titanh3art** [comment]
I merged them. Thanks @God-status
